services:
  wacrm-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    container_name: wacrm_prod
    restart: always
    environment:
      # Expostas para o Frontend/Build
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
      - NEXT_PUBLIC_APP_LOCALE=${NEXT_PUBLIC_APP_LOCALE}

      # Exclusivas do Backend (Segurança e Integrações)
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - META_APP_SECRET=${META_APP_SECRET}
      - META_APP_ID=${META_APP_ID}

      # Configurações do Sistema
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wacrm.rule=Host(`crm.techrocket.site`)"
      - "traefik.http.routers.wacrm.entrypoints=websecure"
      - "traefik.http.routers.wacrm.tls.certresolver=lets-encrypt"
      - "traefik.http.services.wacrm.loadbalancer.server.port=3000"

networks:
  web:
    external: true
